name: Test Coveralls

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.16.5'
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter test --coverage ./test/
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info